name: mocksipipeline
channels:
- conda-forge
dependencies:
- python=3.10
- pip
- pip:
  - ipykernel
  - ipywidgets
  - sunpy[all]
  - asdf
  - ndcube
  - hissw
  - git+https://github.com/sunpy/sunkit-dem.git@main
   #- git+https://github.com/wtbarnes/mocksipipeline.git@main
