name: mocksipipeline
channels:
- conda-forge
dependencies:
- python=3.10
- nodejs
- pip
- pip:
  - jupyterlab
  - distributed
  - dask_labextension
  - bokeh==2.4.2
  - ipykernel
  - ipywidgets
  - sunpy[all]
  - asdf
  - ndcube
  - hissw
  - git+https://github.com/sunpy/sunkit-dem.git@main
   #- git+https://github.com/wtbarnes/mocksipipeline.git@main
